### ISSUE TITLE
Job for Girmal

### ISSUE THREAD

**Issue by craigvl** [craigvl/bunchyAndroid#70]
Update readme with favourite band

**Comment by thierryx96** [comment]
A user is willing to sponsor this issue through gitman.app.   

Using [gitman.app](www.gitman.app) developers get rewarded for contributing to repositories. 

To allow this repository's issues to be sponsored, the owner of this repository needs to take steps below:

- signup to the Gitman platform at [live.gitman.app](https://live.gitman.app/repos/161002648)
- click "enable repo", this can be reverted at any time   
- at that point people are able to sponsor issues for this repository
- developers can submit their work through pull requests 
- once reviewed and merged they will be automatically rewarded 

More info regarding gitman is available at www.gitman.app and a video explaining the workflow can be viewed at https://youtu.be/pw3AFkWl2qc.

If you have any questions, feel free to join the community at https://t.me/joinchat/Gr-5fxF7FTHdNfzKQKJGgQ.
